version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 6
    groups:
      seed-design:
        patterns:
          - "@seed-design/*"
      tanstack:
        patterns:
          - "@tanstack/*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    groups:
      github-actions:
        patterns:
          - "*"
