/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as WizardRouteImport } from "./routes/wizard";
import { Route as ProductsProductIdRouteImport } from "./routes/products.$productId";
import { Route as ProductsNewRouteImport } from "./routes/products.new";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const WizardRoute = WizardRouteImport.update({
  id: "/wizard",
  path: "/wizard",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: "/products/$productId",
  path: "/products/$productId",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: "/products/new",
  path: "/products/new",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/settings": typeof SettingsRoute;
  "/wizard": typeof WizardRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/settings": typeof SettingsRoute;
  "/wizard": typeof WizardRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/settings": typeof SettingsRoute;
  "/wizard": typeof WizardRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/settings"
    | "/wizard"
    | "/products/$productId"
    | "/products/new";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/settings"
    | "/wizard"
    | "/products/$productId"
    | "/products/new";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/settings"
    | "/wizard"
    | "/products/$productId"
    | "/products/new";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  ProfileRoute: typeof ProfileRoute;
  SettingsRoute: typeof SettingsRoute;
  WizardRoute: typeof WizardRoute;
  ProductsProductIdRoute: typeof ProductsProductIdRoute;
  ProductsNewRoute: typeof ProductsNewRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/wizard": {
      id: "/wizard";
      path: "/wizard";
      fullPath: "/wizard";
      preLoaderRoute: typeof WizardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/$productId": {
      id: "/products/$productId";
      path: "/products/$productId";
      fullPath: "/products/$productId";
      preLoaderRoute: typeof ProductsProductIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/new": {
      id: "/products/new";
      path: "/products/new";
      fullPath: "/products/new";
      preLoaderRoute: typeof ProductsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  WizardRoute: WizardRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
