/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ProductsProductIdRouteImport } from "./routes/products.$productId";
import { Route as ProductsNewRouteImport } from "./routes/products.new";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: "/products/$productId",
  path: "/products/$productId",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: "/products/new",
  path: "/products/new",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/settings" | "/products/$productId" | "/products/new";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/settings" | "/products/$productId" | "/products/new";
  id: "__root__" | "/" | "/settings" | "/products/$productId" | "/products/new";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  ProductsProductIdRoute: typeof ProductsProductIdRoute;
  ProductsNewRoute: typeof ProductsNewRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/$productId": {
      id: "/products/$productId";
      path: "/products/$productId";
      fullPath: "/products/$productId";
      preLoaderRoute: typeof ProductsProductIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/new": {
      id: "/products/new";
      path: "/products/new";
      fullPath: "/products/new";
      preLoaderRoute: typeof ProductsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
