import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildSeedTokenCatalog, type SeedTokenCatalog } from "./lib/seed-tokens.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const TOKENS_FILE = join(ROOT, ".seed/tokens.json");
const RULE_FILE = join(ROOT, ".cursor/rules/_generated-seed-tokens.mdc");

/** Fetched by `pnpm seed:sync` so agents can read SEED docs without network access. */
const LLMS_DOCS = {
  "react-index.txt": "https://seed-design.io/react/llms.txt",
  "foundations-index.txt": "https://seed-design.io/foundations/llms.txt",
  "tailwind-css.txt": "https://seed-design.io/llms/react/getting-started/styling/tailwind-css.txt",
  "theming.txt": "https://seed-design.io/llms/react/getting-started/styling/theming.txt",
  "cli-commands.txt": "https://seed-design.io/llms/react/getting-started/cli/commands.txt",
};

const check = process.argv.includes("--check");
const offline = check || process.argv.includes("--offline");

async function main(): Promise<void> {
  const catalog = await buildSeedTokenCatalog();
  const tokensJson = `${JSON.stringify(catalog, null, 2)}\n`;
  const ruleMarkdown = renderRule(catalog);

  if (check) {
    const drifted = [
      await isStale(TOKENS_FILE, tokensJson),
      await isStale(RULE_FILE, ruleMarkdown),
    ].some(Boolean);

    if (drifted) {
      console.error("SEED token catalog is out of date. Run `pnpm seed:sync`.");
      process.exit(1);
    }

    console.log("SEED token catalog is up to date.");
    return;
  }

  await writeFileEnsured(TOKENS_FILE, tokensJson);
  await writeFileEnsured(RULE_FILE, ruleMarkdown);
  console.log(`Wrote ${relative(TOKENS_FILE)} and ${relative(RULE_FILE)}.`);

  if (!offline) {
    await syncDocs();
  }
}

async function syncDocs(): Promise<void> {
  const results = await Promise.allSettled(
    Object.entries(LLMS_DOCS).map(async ([name, url]) => {
      const response = await fetch(url);
      if (!response.ok) throw new Error(`${url} responded ${response.status}`);
      await writeFileEnsured(join(ROOT, ".seed/llms", name), await response.text());
      return name;
    }),
  );

  const failed = results.filter((result) => result.status === "rejected");
  if (failed.length > 0) {
    console.warn(`Skipped ${failed.length} SEED doc(s); the cached copies are still in place.`);
  }
  console.log(`Synced ${results.length - failed.length}/${results.length} SEED docs.`);
}

function renderRule(catalog: SeedTokenCatalog): string {
  const versions = Object.entries(catalog.versions)
    .map(([name, version]) => `${name}@${version}`)
    .join(", ");

  const section = (title: string, values: string[] | undefined) =>
    values && values.length > 0 ? `### ${title}\n\n\`${values.join("`, `")}\`\n` : "";

  return `---
description: The exact SEED design tokens available as Tailwind utilities in this project. Consult before writing any className.
globs: ["src/**/*.tsx", "src/**/*.ts"]
alwaysApply: false
---

# SEED token catalog (generated)

Generated by \`pnpm seed:sync\` from ${versions}. Do not edit by hand.

Any utility built from a token outside this catalog produces **no CSS at all**, because
\`src/app/styles/global.css\` deletes Tailwind's built-in theme. \`bg-red-500\`, \`p-4\`,
\`text-lg\` and \`rounded-md\` silently do nothing.

## Colour tokens

Used by \`bg-\`, \`text-\`, \`border-\`, \`fill-\`, \`stroke-\`, \`ring-\`, \`outline-\`, \`decoration-\`,
\`accent-\`, \`caret-\`, \`shadow-\`, \`from-\`, \`via-\`, \`to-\`.
Example: \`bg-bg-layer-default\`, \`text-fg-neutral\`, \`border-stroke-neutral-muted\`.

${section(
  "Semantic",
  catalog.namespaces.color?.filter((token) => !token.startsWith("palette-")),
)}
${section(
  "Palette",
  catalog.namespaces.color?.filter((token) => token.startsWith("palette-")),
)}
## Dimension tokens

Used by \`p-\`, \`px-\`, \`py-\`, \`pt-\`, \`pr-\`, \`pb-\`, \`pl-\`, \`m-\`, \`w-\`, \`h-\`, \`size-\`,
\`gap-\`, \`gap-x-\`, \`gap-y-\`, and the project's re-mapped \`top-\`, \`right-\`, \`bottom-\`,
\`left-\`, \`inset-\`, \`space-x-\`, \`space-y-\`, \`translate-x-\`, \`translate-y-\`.
Example: \`p-x4\`, \`gap-x3\`, \`top-x2\`.

${section("Dimension", catalog.namespaces.dimension)}
## Radius, shadow, motion

${section("radius (rounded-*)", catalog.namespaces.radius)}
${section("shadow (shadow-*)", catalog.namespaces.shadow)}
${section("duration (duration-*)", catalog.namespaces.duration)}
${section("timing-function (easing-*)", catalog.namespaces["timing-function"])}
## Typography

Apply a complete text style with one class instead of composing size and weight.

${section("Text style utilities", catalog.staticUtilities)}
${section("font-weight (font-*)", catalog.namespaces["font-weight"])}
${section("font-size (text-size-*)", catalog.namespaces["font-size"])}
${section("line-height (leading-*)", catalog.namespaces["line-height"])}
## Functional utility prefixes defined by SEED

${section("Prefixes", catalog.functionalUtilities)}`;
}

async function isStale(path: string, expected: string): Promise<boolean> {
  const actual = await readFile(path, "utf8").catch(() => null);
  if (actual === expected) return false;
  console.error(`Out of date: ${relative(path)}`);
  return true;
}

async function writeFileEnsured(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, "utf8");
}

function relative(path: string): string {
  return path.slice(ROOT.length + 1);
}

await main();
